version: '3.5'
services:
  squidex_mongo:
    image: "mongo:6"
    volumes:
      - /etc/squidex/mongo/db:/data/db
    networks:
      - internal
    restart: unless-stopped

  squidex_squidex:
    image: "squidex/squidex:7"
    ports:
      - "80:80"
    environment:
      - URLS__BASEURL=http://localhost
      - EVENTSTORE__TYPE=MongoDB
      - EVENTSTORE__MONGODB__CONFIGURATION=mongodb://squidex_mongo
      - STORE__MONGODB__CONFIGURATION=mongodb://squidex_mongo
      - IDENTITY__ADMINEMAIL=admin@admin.com
      - IDENTITY__ADMINPASSWORD=password
      - IDENTITY__OIDCNAME=OIDC
      - IDENTITY__OIDCAUTHORITY=https://dev-gl5uck3rwsnmtx8d.us.auth0.com/
      - IDENTITY__OIDCCLIENT=joG6FKco28bHV4cX70janXIdcX2eySSm
      - IDENTITY__OIDCSECRET=HJhAAjTpTD75FcUiEarEDYKf4-f10iCxNIJQOICzo6IsQWUS9ogUJGcJxd-lqU1m
      - IDENTITY__OIDCSCOPES__0=openid
      - IDENTITY__OIDCSCOPES__1=email
      - IDENTITY__OIDCRESPONSETYPE=code
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/healthz"]
      start_period: 60s
    depends_on:
      - squidex_mongo
    volumes:
      - /etc/squidex/assets:/app/Assets
    networks:
      - internal
    restart: unless-stopped
    
networks:
  internal:
    driver: bridge
