version: '3.5'
services:
  squidex_mongo:
    image: "mongo:6"
    volumes:
      - /etc/squidex/mongo/db:/data/db
    networks:
      - internal
    restart: unless-stopped

  minio:
    image: minio/minio
    volumes:
      - /etc/squidex/minio2:/data1
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server --address ":9000" --console-address ":9001" /data1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  keycloack_service:
    image: "quay.io/keycloak/keycloak:26.1.1"
    volumes:
      - "/etc/squidex/keycloak/data:/opt/keycloak/data/import"
    ports:
      - "5489:8080"
    command: start-dev --import-realm
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin

  squidex_squidex:
    image: "squidex/squidex:7"
    extra_hosts:
      - "custom.local:host-gateway"
    ports:
      - "80:80"
    environment:
      - URLS__BASEURL=http://localhost
      - EVENTSTORE__TYPE=MongoDB
      - EVENTSTORE__MONGODB__CONFIGURATION=mongodb://squidex_mongo
      - STORE__MONGODB__CONFIGURATION=mongodb://squidex_mongo
      - IDENTITY__ADMINEMAIL=admin@admin.com
      - IDENTITY__ADMINPASSWORD=password
      # OIDC external
      - IDENTITY__GOOGLECLIENT=
      - IDENTITY__GOOGLESECRET=
      - IDENTITY__GITHUBCLIENT=
      - IDENTITY__GITHUBSECRET=
      - IDENTITY__MICROSOFTCLIENT=
      - IDENTITY__MICROSOFTSECRET=
      # OIDC custom
      - IDENTITY__OIDCNAME=OIDC
      - IDENTITY__OIDCAUTHORITY=http://custom.local:5489/realms/custom
      - IDENTITY__OIDCCLIENT=custom-id
      - IDENTITY__OIDCSECRET=
      - IDENTITY__OIDCSCOPES__0=openid
      - IDENTITY__OIDCSCOPES__1=email
      - IDENTITY__OIDCRESPONSETYPE=code
      # S3 settings
      - ASSETSTORE__TYPE=AmazonS3
      - ASSETSTORE__REGIONNAME=us-east-1
      - ASSETSTORE__AMAZONS3__SERVICEURL=http://host.docker.internal:9000
      - ASSETSTORE__AMAZONS3__BUCKET=test-bucket
      - ASSETSTORE__AMAZONS3__FORCEPATHSTYLE=true
      - ASSETSTORE__AMAZONS3__ACCESSKEY=MstsPeM5Il63FRqdGyY3
      - ASSETSTORE__AMAZONS3__SECRETKEY=HvaNhQ0zSFxMzz5SwRjwJuqhzDV0rAl1QeqCr2By
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/healthz"]
      start_period: 60s
    depends_on:
      - squidex_mongo
    volumes:
      - /etc/squidex/assets:/app/Assets
    networks:
      - internal
    restart: unless-stopped
    
networks:
  internal:
    driver: bridge
